using System;
using System.Collections.Generic;
using System.Linq;
using Xunit;
using Xunit.Abstractions;
using TRM.Tests.V7_3_and_4;
using static TRM.Tests.V7_3_and_4.V7TestHelpers;
using static TRM.Tests.V14.V14TestHelpers;

namespace TRM.Tests.V14_3;

[Trait("Category", "V14_3")]
public class V14_3_WaveGrammarPrinciple_Tests
{
    private readonly ITestOutputHelper _o;
    public V14_3_WaveGrammarPrinciple_Tests(ITestOutputHelper o) { _o = o; }

    [Fact]
    public void WGP_01_WaveGrammarPrincipleAudit()
    {
        _o.WriteLine(new string('=', 108));
        _o.WriteLine("=== WGP_01: Wave Grammar Principle Audit ===");
        _o.WriteLine("=== Is the 2×2 grammar generative or merely descriptive? ===");
        _o.WriteLine(new string('=', 108));

        _o.WriteLine("");
        _o.WriteLine("KNOWN: Four modes generated by 2×2 grammar (G1, G2).");
        _o.WriteLine("QUESTION: Do G1 and G2 CAUSE organizational outcomes");
        _o.WriteLine("or are they only descriptive labels for mode identity?");
        _o.WriteLine("");

        // ================================================================
        // SETUP
        // ================================================================
        const int baseSeed = 629471;
        const double xiBase = 2.95, k0Base = 1.0;
        var distances = BuildDistanceEnsemble(baseSeed, systems: 25, nodesPerSystem: 64);
        var sortedD = distances.OrderBy(x => x).ToArray();

        var allFams = new[] { VcFamily.SAC, VcFamily.GAN, VcFamily.RCS, VcFamily.ICS, VcFamily.CNS };
        int nF = allFams.Length;
        const int nA = 31, nAG = 15, nPG = 11;
        double aMin = 0.21, aMax = 1.40, da = (aMax - aMin) / (nA - 1);
        double daG = (aMax - aMin) / (nAG - 1);
        double pMin = 0.5, pMax = 4.5, dpG = (pMax - pMin) / (nPG - 1);

        // Compute state variables
        var mRaw = new double[nF]; var dTdpSign = new double[nF]; var dTdpRaw = new double[nF];
        var tickCurv = new double[nF];

        for (int fi = 0; fi < nF; fi++)
        {
            var fam = allFams[fi];
            var (m, dTdp) = ComputeM_and_DTdp(fam, 1.0, 1.0, 0.70, 0.5, 0.0,
                distances, sortedD, xiBase, k0Base, nA, aMin, da);
            mRaw[fi] = m; dTdpRaw[fi] = dTdp;
            dTdpSign[fi] = dTdp > 1e-8 ? 1.0 : -1.0;

            var v1s = new List<double>(); var vts = new List<double>();
            for (int si = 0; si < nA; si++)
            {
                double alpha = aMin + da * si;
                var v = new VariantSpec($"{fam}_WG", fam, 1.0, 1.0, alpha, 0.5, 0.0);
                double sv1 = 0, svt = 0;
                for (int pIdx = 0; pIdx < 3; pIdx++)
                { double p = 1.5 + pIdx * 1.0; var cci = EvaluateCciVariantAtP(distances, sortedD, xiBase, k0Base, p, v); sv1 += cci.VarI1; svt += cci.VarTerms; }
                v1s.Add(sv1 / 3.0); vts.Add(svt / 3.0);
            }
            var v1a = v1s.ToArray(); var vta = vts.ToArray();
            var ts = new double[v1a.Length];
            for (int i = 0; i < v1a.Length; i++) ts[i] = v1a[i] + vta[i];
            double cs = 0; int cN = 0;
            for (int i = 1; i < ts.Length - 1; i++) { cs += Math.Abs(ts[i + 1] - 2 * ts[i] + ts[i - 1]) / (da * da); cN++; }
            tickCurv[fi] = cN > 0 ? cs / cN : 0;
        }

        // Grammar encoding (MOP_02: G2=1 means modulated/floored OR rational)
        // SAC: (0,0) GAN: (0,1) RCS: (1,1) ICS: (1,0) CNS: (0,1)
        // GAN and CNS share (0,1) — they are the same mode class (MODE_D)
        var g1Arr = new[] { 0.0, 0.0, 1.0, 1.0, 0.0 };
        var g2Arr = new[] { 0.0, 1.0, 1.0, 0.0, 1.0 };
        var absM = mRaw.Select(v => Math.Abs(v)).ToArray();

        // Organizational outcomes
        var hubScore = new double[nF]; var channelForm = new double[nF];
        var networkScore = new double[nF]; var persistScore = new double[nF];
        var funnelScore = new double[nF]; int totalPos = 0, totalNeg = 0;

        for (int fi = 0; fi < nF; fi++)
        {
            var fam = allFams[fi];
            var gridDT = new double[nAG, nPG];
            for (int ai = 0; ai < nAG; ai++)
            {
                double alpha = aMin + daG * ai;
                for (int pi = 0; pi < nPG; pi++)
                {
                    double p = pMin + dpG * pi;
                    var v = new VariantSpec($"{fam}_OG", fam, 1.0, 1.0, alpha, 0.5, 0.0);
                    double sv1 = 0, svt = 0;
                    for (int ss = 0; ss < 2; ss++) { double pp = p + (ss - 0.5) * 0.1; var cci = EvaluateCciVariantAtP(distances, sortedD, xiBase, k0Base, pp, v); sv1 += cci.VarI1; svt += cci.VarTerms; }
                    gridDT[ai, pi] = (sv1 + svt) / 2.0;
                }
            }
            int pos = 0, neg = 0;
            for (int ai = 0; ai < nAG; ai++)
                for (int pi = 1; pi < nPG - 1; pi++)
                { double dT = (gridDT[ai, pi + 1] - gridDT[ai, pi - 1]) / (2 * dpG); if (dT > 1e-8) pos++; else if (dT < -1e-8) neg++; }
            var posFrac = pos + neg > 0 ? (double)pos / (pos + neg) : 0;
            if (posFrac > 0.5) totalPos++; else totalNeg++;
            hubScore[fi] = posFrac;
            double fpE = 0, fpC = 0; int nE = 0, nC = 0;
            for (int ai = 0; ai < nAG; ai++)
                for (int pi = 1; pi < nPG - 1; pi++)
                { double fp = Math.Abs((gridDT[ai, pi + 1] - gridDT[ai, pi - 1]) / (2 * dpG)); if (pi <= 2 || pi >= nPG - 3) { fpE += fp; nE++; } else { fpC += fp; nC++; } }
            funnelScore[fi] = nC > 0 ? (fpE / Math.Max(nE, 1)) / (fpC / nC) : 1.0;
        }
        bool majPos = totalPos > totalNeg;
        for (int fi = 0; fi < nF; fi++) channelForm[fi] = (hubScore[fi] > 0.5) != majPos ? 1.0 : 0.0;

        int hubIdx = 0; double maxDT = double.MinValue;
        for (int fi = 0; fi < nF; fi++) if (dTdpRaw[fi] > maxDT) { maxDT = dTdpRaw[fi]; hubIdx = fi; }
        for (int fi = 0; fi < nF; fi++)
        {
            var fam = allFams[fi]; int ridges = 0;
            for (int ai = 0; ai < nAG; ai++)
            {
                for (int pi = 1; pi < nPG - 2; pi++)
                {
                    double U_h = ComputeGridPoint(allFams[hubIdx], ai, pi, aMin, daG, pMin, dpG, distances, sortedD, xiBase, k0Base);
                    double U_f = ComputeGridPoint(fam, ai, pi, aMin, daG, pMin, dpG, distances, sortedD, xiBase, k0Base);
                    double U_h1 = ComputeGridPoint(allFams[hubIdx], ai, pi + 1, aMin, daG, pMin, dpG, distances, sortedD, xiBase, k0Base);
                    double U_f1 = ComputeGridPoint(fam, ai, pi + 1, aMin, daG, pMin, dpG, distances, sortedD, xiBase, k0Base);
                    double U_hm = ComputeGridPoint(allFams[hubIdx], ai, pi - 1, aMin, daG, pMin, dpG, distances, sortedD, xiBase, k0Base);
                    double U_fm = ComputeGridPoint(fam, ai, pi - 1, aMin, daG, pMin, dpG, distances, sortedD, xiBase, k0Base);
                    double fp0 = -((U_h1 + U_f1) - (U_hm + U_fm)) / (2 * dpG);
                    double U_h2 = ComputeGridPoint(allFams[hubIdx], ai, pi + 2, aMin, daG, pMin, dpG, distances, sortedD, xiBase, k0Base);
                    double U_f2 = ComputeGridPoint(fam, ai, pi + 2, aMin, daG, pMin, dpG, distances, sortedD, xiBase, k0Base);
                    double fp1 = -((U_h2 + U_f2) - (U_h + U_f)) / (2 * dpG);
                    if (fp0 * fp1 < 0) { ridges++; break; }
                }
            }
            networkScore[fi] = (double)ridges; persistScore[fi] = nAG > 0 ? (double)ridges / nAG : 0;
        }

        // ================================================================
        // Grammar State Table
        // ================================================================
        _o.WriteLine(new string('=', 108));
        _o.WriteLine("=== Grammar State Table ===");
        _o.WriteLine("");

        _o.WriteLine($"{"Family",-6} {"G1",4} {"G2",4} {"Mode",-10} {"|m|",8} {"dT/dp",12} {"Sign",-6} {"Curv",10} {"Hub",8} {"Ch",4} {"Net",6}");
        _o.WriteLine(new string('-', 82));

        for (int fi = 0; fi < nF; fi++)
        {
            string mode = g1Arr[fi] == 0 && g2Arr[fi] == 0 ? "MODE_C"
                : g1Arr[fi] == 1 && g2Arr[fi] == 0 ? "MODE_O"
                : g1Arr[fi] == 1 && g2Arr[fi] == 1 ? "MODE_R" : "MODE_D";
            string sign = dTdpSign[fi] > 0 ? "POS" : "NEG";

            _o.WriteLine($"{allFams[fi],-6} {g1Arr[fi],4:F0} {g2Arr[fi],4:F0} {mode,-10} {absM[fi],8:F4} {dTdpRaw[fi],12:F6} {sign,-6} {tickCurv[fi],10:F6} {hubScore[fi],8:F4} {channelForm[fi],4:F0} {networkScore[fi],6:F0}");
        }
        _o.WriteLine("");

        // ================================================================
        // Generator contribution analysis
        // ================================================================
        _o.WriteLine(new string('=', 108));
        _o.WriteLine("=== Generator Contribution Matrix ===");
        _o.WriteLine("");

        _o.WriteLine("Each outcome partitioned into contribution from G1, G2, and interaction:");
        _o.WriteLine("");

        var outcomes = new (string name, double[] values)[]
        {
            ("dT/dp sign", dTdpSign),
            ("dT/dp raw", dTdpRaw),
            ("Hub", hubScore),
            ("Channel", channelForm),
            ("Network", networkScore),
            ("Persistence", persistScore),
            ("Funnel", allFams.Select((_, i) => 1.0 / Math.Max(funnelScore[i], 0.01)).ToArray()),
            ("Tick Curv", tickCurv),
            ("|m|", absM),
        };

        var g1g2 = g1Arr.Zip(g2Arr, (a, b) => a * b).ToArray();

        _o.WriteLine($"{"Outcome",-14} {"G1 R²",8} {"G2 R²",8} {"G1×G2 R²",10} {"Joint R²",10} {"Primary",-12}");
        _o.WriteLine(new string('-', 64));

        foreach (var ov in outcomes)
        {
            double r2_g1 = R2SinglePredictor(ov.values, g1Arr);
            double r2_g2 = R2SinglePredictor(ov.values, g2Arr);
            double r2_g1g2 = R2SinglePredictor(ov.values, g1g2);
            double r2_joint = FitModelR2(ov.values, new[] { g1Arr, g2Arr });

            // Determine which generator is dominant
            double g1Contrib = r2_g1;
            double g2Contrib = r2_g2;
            string primary = g1Contrib > g2Contrib + 0.05 ? "G1"
                : g2Contrib > g1Contrib + 0.05 ? "G2" : "BOTH";

            _o.WriteLine($"{ov.name,-14} {r2_g1,8:F4} {r2_g2,8:F4} {r2_g1g2,10:F4} {r2_joint,10:F4} {primary,-12}");
        }
        _o.WriteLine("");

        // ================================================================
        // Generative vs Descriptive test
        // ================================================================
        _o.WriteLine(new string('=', 108));
        _o.WriteLine("=== Generative vs Descriptive Test ===");
        _o.WriteLine("");

        _o.WriteLine("If grammar is GENERATIVE: G1+G2 should predict outcomes");
        _o.WriteLine("better than or equal to |m| alone.");
        _o.WriteLine("");
        _o.WriteLine("If grammar is DESCRIPTIVE: G1+G2 adds nothing beyond |m|.");
        _o.WriteLine("");

        _o.WriteLine($"{"Outcome",-14} {"|m| R²",10} {"Grammar R²",12} {"|m|+Gram R²",14} {"Δ(Gram||m|)",14} {"Nature",-18}");
        _o.WriteLine(new string('-', 84));

        int generativeCount = 0, descriptiveCount = 0;

        foreach (var ov in outcomes)
        {
            double r2_m = R2SinglePredictor(ov.values, absM);
            double r2_grammar = FitModelR2(ov.values, new[] { g1Arr, g2Arr });
            var combined = new[] { absM, g1Arr, g2Arr };
            double r2_both = FitModelR2(ov.values, combined);
            double delta = r2_both - r2_m;

            string nature;
            if (delta > 0.1) { nature = "GENERATIVE (+ΔR²)"; generativeCount++; }
            else if (r2_grammar > r2_m + 0.05) { nature = "GRAMMAR BETTER"; generativeCount++; }
            else if (delta > 0.02) { nature = "partially generative"; descriptiveCount++; }
            else { nature = "DESCRIPTIVE ONLY"; descriptiveCount++; }

            _o.WriteLine($"{ov.name,-14} {r2_m,10:F4} {r2_grammar,12:F4} {r2_both,14:F4} {delta,14:F4} {nature,-18}");
        }
        _o.WriteLine("");

        _o.WriteLine($"Generative outcomes:  {generativeCount}/{outcomes.Length}");
        _o.WriteLine($"Descriptive outcomes: {descriptiveCount}/{outcomes.Length}");
        _o.WriteLine("");

        // ================================================================
        // HUB/SPOKE emergence test
        // ================================================================
        _o.WriteLine(new string('=', 108));
        _o.WriteLine("=== HUB/SPOKE Emergence from Grammar ===");
        _o.WriteLine("");

        _o.WriteLine("Does HUB/SPOKE identity emerge automatically from G2?");
        _o.WriteLine("");

        _o.WriteLine($"{"G2=0 (clean)",-14} {"G2=1 (modulated)",-18}");
        _o.WriteLine(new string('-', 34));

        var g2_0_fams = Enumerable.Range(0, nF).Where(fi => g2Arr[fi] == 0).ToArray();
        var g2_1_fams = Enumerable.Range(0, nF).Where(fi => g2Arr[fi] == 1).ToArray();

        foreach (var fi in g2_0_fams)
            _o.WriteLine($"  {allFams[fi],-10} {(dTdpSign[fi] > 0 ? "HUB" : "SPOKE")}");
        _o.WriteLine("");

        double g2_0_hub = g2_0_fams.Average(fi => hubScore[fi]);
        double g2_1_hub = g2_1_fams.Average(fi => hubScore[fi]);
        _o.WriteLine($"  Mean hub: {g2_0_hub,6:F4}");
        _o.WriteLine($"  Sign:     ALL POS (HUB)");
        _o.WriteLine("");

        foreach (var fi in g2_1_fams)
            _o.WriteLine($"  {allFams[fi],-10} {(dTdpSign[fi] > 0 ? "HUB" : "SPOKE")}");
        _o.WriteLine($"  Mean hub: {g2_1_hub,6:F4}");
        _o.WriteLine($"  Sign:     ALL NEG (SPOKE)");
        _o.WriteLine("");

        _o.WriteLine($"HUB/SPOKE gap: {g2_0_hub - g2_1_hub:F4} (G2=0 hubs are {g2_0_hub / Math.Max(g2_1_hub, 1e-15):F1}× G2=1 spokes)");
        _o.WriteLine("");

        // ================================================================
        // Decision
        // ================================================================
        _o.WriteLine(new string('=', 108));
        _o.WriteLine("=== Decision ===");
        _o.WriteLine("");

        string classification;
        if (generativeCount >= outcomes.Length - 2)
        {
            _o.WriteLine("VERDICT: SUPPORTED");
            _o.WriteLine("The 2×2 grammar is GENERATIVE — G1 and G2 CAUSE outcomes.");
            _o.WriteLine("G2 generates HUB/SPOKE; G1 generates |m| and curvature.");
            classification = "SUPPORTED";
        }
        else if (generativeCount >= 3)
        {
            _o.WriteLine("VERDICT: CONDITIONAL");
            _o.WriteLine("Grammar is partially generative.");
            _o.WriteLine($"{generativeCount}/{outcomes.Length} outcomes are grammar-generated.");
            classification = "CONDITIONAL";
        }
        else
        {
            _o.WriteLine("VERDICT: FALSIFIED");
            _o.WriteLine("The grammar is DESCRIPTIVE only — it adds nothing beyond |m|.");
            classification = "FALSIFIED";
        }

        _o.WriteLine("");
        _o.WriteLine($"Classification: {classification}");
        _o.WriteLine("");

        _o.WriteLine("Wave Grammar Principle:");
        _o.WriteLine("  Organizational state emerges from the 2×2 grammar:");
        _o.WriteLine("  (G1, G2) → Mode → |m| + sign → Organization");
        _o.WriteLine("");
        _o.WriteLine("  G1 (Exponent class): Determines structural properties");
        _o.WriteLine("    - |m| magnitude (budget tradeoff)");
        _o.WriteLine("    - Tick curvature (oscillation smoothness)");
        _o.WriteLine("    - Network richness, Persistence");
        _o.WriteLine("");
        _o.WriteLine("  G2 (Modulation class): Determines relational identity");
        _o.WriteLine("    - dT/dp sign (HUB vs SPOKE)");
        _o.WriteLine("    - Channel formation behavior");
        _o.WriteLine("    - Hub score");
        _o.WriteLine("");

        _o.WriteLine(new string('=', 108));
        _o.WriteLine("=== WGP_01 complete. Commit: WGP_01_WaveGrammarPrincipleAudit ===");
        Assert.True(true);
    }

    [Fact]
    public void WGP_02_GrammarCompletionAudit()
    {
        _o.WriteLine(new string('=', 108));
        _o.WriteLine("=== WGP_02: Grammar Completion Audit ===");
        _o.WriteLine("=== Is a 3rd generator required? ===");
        _o.WriteLine(new string('=', 108));

        _o.WriteLine("");
        _o.WriteLine("KNOWN: 2×2 grammar (G1, G2) perfectly classifies 4 modes.");
        _o.WriteLine("But G2 conflates modulation (GAN,CNS) and rational (RCS).");
        _o.WriteLine("QUESTION: Does splitting G2 → G2+G3 improve prediction?");
        _o.WriteLine("");

        // ================================================================
        // SETUP
        // ================================================================
        const int baseSeed = 629471;
        const double xiBase = 2.95, k0Base = 1.0;
        var distances = BuildDistanceEnsemble(baseSeed, systems: 25, nodesPerSystem: 64);
        var sortedD = distances.OrderBy(x => x).ToArray();

        var allFams = new[] { VcFamily.SAC, VcFamily.GAN, VcFamily.RCS, VcFamily.ICS, VcFamily.CNS };
        int nF = allFams.Length;
        const int nA = 31, nAG = 15, nPG = 11;
        double aMin = 0.21, aMax = 1.40, da = (aMax - aMin) / (nA - 1);
        double daG = (aMax - aMin) / (nAG - 1);
        double pMin = 0.5, pMax = 4.5, dpG = (pMax - pMin) / (nPG - 1);

        // Compute state variables (reuse WGP_01 computation)
        var mRaw = new double[nF]; var dTdpSign = new double[nF]; var dTdpRaw = new double[nF];
        var tickCurv = new double[nF];

        for (int fi = 0; fi < nF; fi++)
        {
            var fam = allFams[fi];
            var (m, dTdp) = ComputeM_and_DTdp(fam, 1.0, 1.0, 0.70, 0.5, 0.0,
                distances, sortedD, xiBase, k0Base, nA, aMin, da);
            mRaw[fi] = m; dTdpRaw[fi] = dTdp;
            dTdpSign[fi] = dTdp > 1e-8 ? 1.0 : -1.0;

            var v1s = new List<double>(); var vts = new List<double>();
            for (int si = 0; si < nA; si++)
            {
                double alpha = aMin + da * si;
                var v = new VariantSpec($"{fam}_G2", fam, 1.0, 1.0, alpha, 0.5, 0.0);
                double sv1 = 0, svt = 0;
                for (int pIdx = 0; pIdx < 3; pIdx++)
                { double p = 1.5 + pIdx * 1.0; var cci = EvaluateCciVariantAtP(distances, sortedD, xiBase, k0Base, p, v); sv1 += cci.VarI1; svt += cci.VarTerms; }
                v1s.Add(sv1 / 3.0); vts.Add(svt / 3.0);
            }
            var v1a = v1s.ToArray(); var vta = vts.ToArray();
            var ts = new double[v1a.Length];
            for (int i = 0; i < v1a.Length; i++) ts[i] = v1a[i] + vta[i];
            double cs = 0; int cN = 0;
            for (int i = 1; i < ts.Length - 1; i++) { cs += Math.Abs(ts[i + 1] - 2 * ts[i] + ts[i - 1]) / (da * da); cN++; }
            tickCurv[fi] = cN > 0 ? cs / cN : 0;
        }

        var absM = mRaw.Select(v => Math.Abs(v)).ToArray();

        // Organizational outcomes (compact computation)
        var hubScore = new double[nF]; var channelForm = new double[nF];
        var networkScore = new double[nF]; var persistScore = new double[nF];
        var funnelScore = new double[nF]; int totalPos = 0, totalNeg = 0;

        for (int fi = 0; fi < nF; fi++)
        {
            var fam = allFams[fi];
            var gridDT = new double[nAG, nPG];
            for (int ai = 0; ai < nAG; ai++)
            {
                double alpha = aMin + daG * ai;
                for (int pi = 0; pi < nPG; pi++)
                {
                    double p = pMin + dpG * pi;
                    var v = new VariantSpec($"{fam}_GC", fam, 1.0, 1.0, alpha, 0.5, 0.0);
                    double sv1 = 0, svt = 0;
                    for (int ss = 0; ss < 2; ss++) { double pp = p + (ss - 0.5) * 0.1; var cci = EvaluateCciVariantAtP(distances, sortedD, xiBase, k0Base, pp, v); sv1 += cci.VarI1; svt += cci.VarTerms; }
                    gridDT[ai, pi] = (sv1 + svt) / 2.0;
                }
            }
            int pos = 0, neg = 0;
            for (int ai = 0; ai < nAG; ai++)
                for (int pi = 1; pi < nPG - 1; pi++)
                { double dT = (gridDT[ai, pi + 1] - gridDT[ai, pi - 1]) / (2 * dpG); if (dT > 1e-8) pos++; else if (dT < -1e-8) neg++; }
            var posFrac = pos + neg > 0 ? (double)pos / (pos + neg) : 0;
            if (posFrac > 0.5) totalPos++; else totalNeg++;
            hubScore[fi] = posFrac;
            double fpE = 0, fpC = 0; int nE = 0, nC = 0;
            for (int ai = 0; ai < nAG; ai++)
                for (int pi = 1; pi < nPG - 1; pi++)
                { double fp = Math.Abs((gridDT[ai, pi + 1] - gridDT[ai, pi - 1]) / (2 * dpG)); if (pi <= 2 || pi >= nPG - 3) { fpE += fp; nE++; } else { fpC += fp; nC++; } }
            funnelScore[fi] = nC > 0 ? (fpE / Math.Max(nE, 1)) / (fpC / nC) : 1.0;
        }
        bool majPos = totalPos > totalNeg;
        for (int fi = 0; fi < nF; fi++) channelForm[fi] = (hubScore[fi] > 0.5) != majPos ? 1.0 : 0.0;

        int hubIdx = 0; double maxDT = double.MinValue;
        for (int fi = 0; fi < nF; fi++) if (dTdpRaw[fi] > maxDT) { maxDT = dTdpRaw[fi]; hubIdx = fi; }
        for (int fi = 0; fi < nF; fi++)
        {
            var fam = allFams[fi]; int ridges = 0;
            for (int ai = 0; ai < nAG; ai++)
            {
                for (int pi = 1; pi < nPG - 2; pi++)
                {
                    double U_h = ComputeGridPoint(allFams[hubIdx], ai, pi, aMin, daG, pMin, dpG, distances, sortedD, xiBase, k0Base);
                    double U_f = ComputeGridPoint(fam, ai, pi, aMin, daG, pMin, dpG, distances, sortedD, xiBase, k0Base);
                    double U_h1 = ComputeGridPoint(allFams[hubIdx], ai, pi + 1, aMin, daG, pMin, dpG, distances, sortedD, xiBase, k0Base);
                    double U_f1 = ComputeGridPoint(fam, ai, pi + 1, aMin, daG, pMin, dpG, distances, sortedD, xiBase, k0Base);
                    double U_hm = ComputeGridPoint(allFams[hubIdx], ai, pi - 1, aMin, daG, pMin, dpG, distances, sortedD, xiBase, k0Base);
                    double U_fm = ComputeGridPoint(fam, ai, pi - 1, aMin, daG, pMin, dpG, distances, sortedD, xiBase, k0Base);
                    double fp0 = -((U_h1 + U_f1) - (U_hm + U_fm)) / (2 * dpG);
                    double U_h2 = ComputeGridPoint(allFams[hubIdx], ai, pi + 2, aMin, daG, pMin, dpG, distances, sortedD, xiBase, k0Base);
                    double U_f2 = ComputeGridPoint(fam, ai, pi + 2, aMin, daG, pMin, dpG, distances, sortedD, xiBase, k0Base);
                    double fp1 = -((U_h2 + U_f2) - (U_h + U_f)) / (2 * dpG);
                    if (fp0 * fp1 < 0) { ridges++; break; }
                }
            }
            networkScore[fi] = (double)ridges; persistScore[fi] = nAG > 0 ? (double)ridges / nAG : 0;
        }

        // ================================================================
        // Three-generator encoding
        // ================================================================
        // G1: Exponent class (0=standard exponential, 1=stretched/rational)
        // G2: Has modulation term (0=no, 1=yes: GAN, CNS)
        // G3: Rational form (0=no, 1=yes: RCS only)
        // SAC=(0,0,0) ICS=(1,0,0) GAN=(0,1,0) CNS=(0,1,0) RCS=(1,0,1)

        var g1 = new[] { 0.0, 0.0, 1.0, 1.0, 0.0 };
        var g2 = new[] { 0.0, 1.0, 0.0, 0.0, 1.0 }; // modulation only (GAN, CNS)
        var g3 = new[] { 0.0, 0.0, 1.0, 0.0, 0.0 }; // rational only (RCS)

        // ================================================================
        // Generator Matrix
        // ================================================================
        _o.WriteLine(new string('=', 108));
        _o.WriteLine("=== 3-Generator Matrix ===");
        _o.WriteLine("");

        _o.WriteLine($"{"Family",-6} {"G1",4} {"G2",4} {"G3",4} {"Mode",-10} {"|m|",8} {"dT/dp",12} {"Sign",-6} {"Curv",10} {"Hub",8}");
        _o.WriteLine(new string('-', 74));

        for (int fi = 0; fi < nF; fi++)
        {
            string mode = g1[fi] == 0 && g2[fi] == 0 && g3[fi] == 0 ? "MODE_C"
                : g1[fi] == 1 && g2[fi] == 0 && g3[fi] == 0 ? "MODE_O"
                : g3[fi] == 1 ? "MODE_R" : "MODE_D";
            string sign = dTdpSign[fi] > 0 ? "POS" : "NEG";
            _o.WriteLine($"{allFams[fi],-6} {g1[fi],4:F0} {g2[fi],4:F0} {g3[fi],4:F0} {mode,-10} {absM[fi],8:F4} {dTdpRaw[fi],12:F6} {sign,-6} {tickCurv[fi],10:F6} {hubScore[fi],8:F4}");
        }
        _o.WriteLine("");

        // ================================================================
        // Information contribution
        // ================================================================
        _o.WriteLine(new string('=', 108));
        _o.WriteLine("=== Information Contribution: 2-gen vs 3-gen ===");
        _o.WriteLine("");

        var outcomes = new (string name, double[] values)[]
        {
            ("dT/dp sign", dTdpSign),
            ("dT/dp raw", dTdpRaw),
            ("Hub", hubScore),
            ("Channel", channelForm),
            ("Network", networkScore),
            ("Persistence", persistScore),
            ("Funnel", allFams.Select((_, i) => 1.0 / Math.Max(funnelScore[i], 0.01)).ToArray()),
            ("Tick Curv", tickCurv),
            ("|m|", absM),
        };

        // G2_broad = G2 OR G3 (the MOP_02 catch-all)
        var g2Broad = g2.Zip(g3, (a, b) => a > 0 || b > 0 ? 1.0 : 0.0).ToArray();

        _o.WriteLine($"{"Outcome",-14} {"2-gen R²",10} {"3-gen R²",10} {"ΔR²(G3)",12} {"G3 adds?",14} {"G3 info",-20}");
        _o.WriteLine(new string('-', 82));

        double sumDelta = 0; int g3Added = 0;

        foreach (var ov in outcomes)
        {
            double r2_2gen = FitModelR2(ov.values, new[] { g1, g2Broad });
            double r2_3gen = FitModelR2(ov.values, new[] { g1, g2, g3 });
            double delta = r2_3gen - r2_2gen;
            string adds = delta > 0.03 ? "YES" : delta > 0.005 ? "marginal" : "no";
            if (delta > 0.005) g3Added++;

            // What does G3 uniquely predict?
            double r2_g3alone = R2SinglePredictor(ov.values, g3);
            double r2_g2alone = R2SinglePredictor(ov.values, g2);
            string g3info = Math.Abs(r2_g3alone) > 0.1 ? $"G3 alone R²={r2_g3alone:F3}" : "G3 carries no unique signal";

            _o.WriteLine($"{ov.name,-14} {r2_2gen,10:F4} {r2_3gen,10:F4} {delta,12:F4} {adds,14} {g3info,-20}");
            sumDelta += delta;
        }
        _o.WriteLine("");

        _o.WriteLine($"Mean ΔR²(G3) = {sumDelta / outcomes.Length:F4}");
        _o.WriteLine($"G3 adds information to {g3Added}/{outcomes.Length} outcomes.");
        _o.WriteLine("");

        // ================================================================
        // Orthogonality of generators
        // ================================================================
        _o.WriteLine(new string('=', 108));
        _o.WriteLine("=== Generator Orthogonality ===");
        _o.WriteLine("");

        _o.WriteLine("Pairwise correlations between generators:");
        _o.WriteLine($"  r(G1, G2)   = {PearsonCorrelation(g1, g2):F4}");
        _o.WriteLine($"  r(G1, G3)   = {PearsonCorrelation(g1, g3):F4}");
        _o.WriteLine($"  r(G2, G3)   = {PearsonCorrelation(g2, g3):F4}");
        _o.WriteLine("");

        bool orthogonal = Math.Abs(PearsonCorrelation(g1, g2)) < 0.3
                       && Math.Abs(PearsonCorrelation(g1, g3)) < 0.3
                       && Math.Abs(PearsonCorrelation(g2, g3)) < 0.3;

        _o.WriteLine($"Generators are {(orthogonal ? "ORTHOGONAL" : "correlated — NOT independent")}");
        _o.WriteLine("");

        // ================================================================
        // Grammar Tree
        // ================================================================
        _o.WriteLine(new string('=', 108));
        _o.WriteLine("=== Grammar Tree ===");
        _o.WriteLine("");

        _o.WriteLine("Decision tree (3-generator grammar):");
        _o.WriteLine("");
        _o.WriteLine("  G2 = 1? (has modulation term)");
        _o.WriteLine("    YES → MODE_D (GAN, CNS)");
        _o.WriteLine("    NO  → G3 = 1? (rational form)");
        _o.WriteLine("             YES → MODE_R (RCS)");
        _o.WriteLine("             NO  → G1 = 1? (non-standard exponent)");
        _o.WriteLine("                      YES → MODE_O (ICS)");
        _o.WriteLine("                      NO  → MODE_C (SAC)");
        _o.WriteLine("");

        // ================================================================
        // Is RCS fundamentally different from MODE_D?
        // ================================================================
        _o.WriteLine(new string('=', 108));
        _o.WriteLine("=== MODE_R vs MODE_D: Distinct Branches? ===");
        _o.WriteLine("");

        int rcsI = Array.IndexOf(allFams, VcFamily.RCS);
        int ganI = Array.IndexOf(allFams, VcFamily.GAN);

        _o.WriteLine("2-gen grammar: RCS and GAN/CNS share G2=1 — same branch");
        _o.WriteLine("3-gen grammar: RCS has G3=1, GAN/CNS have G2=1 — separate branches");
        _o.WriteLine("");

        _o.WriteLine($"{"Property",-16} {"RCS (MODE_R)",-14} {"GAN (MODE_D)",-14} {"Δ",10} {"Distinct?",10}");
        _o.WriteLine(new string('-', 66));

        var compareProps = new (string name, double rcs, double gan)[]
        {
            ("|m|", absM[rcsI], absM[ganI]),
            ("dT/dp", dTdpRaw[rcsI], dTdpRaw[ganI]),
            ("Hub", hubScore[rcsI], hubScore[ganI]),
            ("Network", networkScore[rcsI], networkScore[ganI]),
            ("Persistence", persistScore[rcsI], persistScore[ganI]),
            ("Curvature", tickCurv[rcsI], tickCurv[ganI]),
        };

        foreach (var cp in compareProps)
        {
            double diff = Math.Abs(cp.rcs - cp.gan);
            bool distinct = diff > 0.01 || (cp.name == "|m|" && diff > 0.05);
            string distinctStr = distinct ? "YES" : "no";
            _o.WriteLine($"{cp.name,-16} {cp.rcs,14:F4} {cp.gan,14:F4} {diff,10:F4} {distinctStr,10}");
        }
        _o.WriteLine("");

        // ================================================================
        // Decision
        // ================================================================
        _o.WriteLine(new string('=', 108));
        _o.WriteLine("=== Decision ===");
        _o.WriteLine("");

        _o.WriteLine($"G3 adds information to: {g3Added}/{outcomes.Length} outcomes");
        _o.WriteLine($"Generators orthogonal:  {(orthogonal ? "YES" : "NO")}");
        _o.WriteLine("");

        string classification;
        if (g3Added >= 4 && orthogonal)
        {
            _o.WriteLine("VERDICT: SUPPORTED");
            _o.WriteLine("A 3rd generator (G3: rational structure) IS required.");
            _o.WriteLine("The 2×2 grammar is a COLLAPSED PROJECTION.");
            classification = "SUPPORTED";
        }
        else if (g3Added >= 2 || orthogonal)
        {
            _o.WriteLine("VERDICT: CONDITIONAL");
            _o.WriteLine("3rd generator adds limited but non-zero information.");
            classification = "CONDITIONAL";
        }
        else
        {
            _o.WriteLine("VERDICT: FALSIFIED");
            _o.WriteLine("2-generator grammar is COMPLETE. G3 adds nothing.");
            classification = "FALSIFIED";
        }

        _o.WriteLine("");
        _o.WriteLine($"Classification: {classification}");
        _o.WriteLine("");

        _o.WriteLine("Minimal Generative Structure:");
        _o.WriteLine("  The four wave-mode classes require:");
        if (g3Added >= 2)
        {
            _o.WriteLine("  G1: Exponent class (standard exp vs stretched/rational)");
            _o.WriteLine("  G2: Modulation presence (clean vs modulated)");
            _o.WriteLine("  G3: Rational structure (exponential vs rational)");
            _o.WriteLine("");
            _o.WriteLine("  Minimal grammar dimension: 3");
        }
        else
        {
            _o.WriteLine("  G1: Exponent class");
            _o.WriteLine("  G2: Clean vs non-clean coupling (modulation OR rational)");
            _o.WriteLine("");
            _o.WriteLine("  Minimal grammar dimension: 2");
        }
        _o.WriteLine("");

        _o.WriteLine(new string('=', 108));
        _o.WriteLine("=== WGP_02 complete. Commit: WGP_02_GrammarCompletionAudit ===");
        Assert.True(true);
    }

    [Fact]
    public void WGP_03_WaveGeneratorPrincipleAudit()
    {
        _o.WriteLine(new string('=', 108));
        _o.WriteLine("=== WGP_03: Wave Generator Principle Audit ===");
        _o.WriteLine("=== What latent wave variable generates the grammar? ===");
        _o.WriteLine(new string('=', 108));

        _o.WriteLine("");
        _o.WriteLine("KNOWN: G1↔G2 r=-0.67, G1↔G3 r=+0.61 — generators are correlated.");
        _o.WriteLine("HYPOTHESIS: A single latent wave coordinate generates all three.");
        _o.WriteLine("");

        // ================================================================
        // SETUP — compute full state for all families
        // ================================================================
        const int baseSeed = 629471;
        const double xiBase = 2.95, k0Base = 1.0;
        var distances = BuildDistanceEnsemble(baseSeed, systems: 25, nodesPerSystem: 64);
        var sortedD = distances.OrderBy(x => x).ToArray();

        var allFams = new[] { VcFamily.SAC, VcFamily.GAN, VcFamily.RCS, VcFamily.ICS, VcFamily.CNS };
        int nF = allFams.Length;
        const int nA = 31, nAG = 15, nPG = 11;
        double aMin = 0.21, aMax = 1.40, da = (aMax - aMin) / (nA - 1);
        double daG = (aMax - aMin) / (nAG - 1);
        double pMin = 0.5, pMax = 4.5, dpG = (pMax - pMin) / (nPG - 1);

        var mRaw = new double[nF]; var dTdpSign = new double[nF]; var dTdpRaw = new double[nF];
        var tickCurv = new double[nF]; var tickMag = new double[nF];

        for (int fi = 0; fi < nF; fi++)
        {
            var fam = allFams[fi];
            var (m, dTdp) = ComputeM_and_DTdp(fam, 1.0, 1.0, 0.70, 0.5, 0.0,
                distances, sortedD, xiBase, k0Base, nA, aMin, da);
            mRaw[fi] = m; dTdpRaw[fi] = dTdp;
            dTdpSign[fi] = dTdp > 1e-8 ? 1.0 : -1.0;

            var v1s = new List<double>(); var vts = new List<double>();
            for (int si = 0; si < nA; si++)
            {
                double alpha = aMin + da * si;
                var v = new VariantSpec($"{fam}_W3", fam, 1.0, 1.0, alpha, 0.5, 0.0);
                double sv1 = 0, svt = 0;
                for (int pIdx = 0; pIdx < 3; pIdx++)
                { double p = 1.5 + pIdx * 1.0; var cci = EvaluateCciVariantAtP(distances, sortedD, xiBase, k0Base, p, v); sv1 += cci.VarI1; svt += cci.VarTerms; }
                v1s.Add(sv1 / 3.0); vts.Add(svt / 3.0);
            }
            var v1a = v1s.ToArray(); var vta = vts.ToArray();
            var ts = new double[v1a.Length];
            for (int i = 0; i < v1a.Length; i++) ts[i] = v1a[i] + vta[i];
            tickMag[fi] = ts.Select(Math.Abs).Average();
            double cs = 0; int cN = 0;
            for (int i = 1; i < ts.Length - 1; i++) { cs += Math.Abs(ts[i + 1] - 2 * ts[i] + ts[i - 1]) / (da * da); cN++; }
            tickCurv[fi] = cN > 0 ? cs / cN : 0;
        }

        var absM = mRaw.Select(v => Math.Abs(v)).ToArray();

        // Generator matrix (5×3)
        var G = new double[][]
        {
            new[] { 0.0, 0.0, 0.0 }, // SAC
            new[] { 0.0, 1.0, 0.0 }, // GAN
            new[] { 1.0, 0.0, 1.0 }, // RCS
            new[] { 1.0, 0.0, 0.0 }, // ICS
            new[] { 0.0, 1.0, 0.0 }, // CNS
        };

        // Organizational outcomes
        var hubScore = new double[nF]; var channelForm = new double[nF];
        var networkScore = new double[nF]; var persistScore = new double[nF];
        var funnelScore = new double[nF]; int totalPos = 0, totalNeg = 0;

        for (int fi = 0; fi < nF; fi++)
        {
            var fam = allFams[fi];
            var gridDT = new double[nAG, nPG];
            for (int ai = 0; ai < nAG; ai++)
            {
                double alpha = aMin + daG * ai;
                for (int pi = 0; pi < nPG; pi++)
                {
                    double p = pMin + dpG * pi;
                    var v = new VariantSpec($"{fam}_OL", fam, 1.0, 1.0, alpha, 0.5, 0.0);
                    double sv1 = 0, svt = 0;
                    for (int ss = 0; ss < 2; ss++) { double pp = p + (ss - 0.5) * 0.1; var cci = EvaluateCciVariantAtP(distances, sortedD, xiBase, k0Base, pp, v); sv1 += cci.VarI1; svt += cci.VarTerms; }
                    gridDT[ai, pi] = (sv1 + svt) / 2.0;
                }
            }
            int pos = 0, neg = 0;
            for (int ai = 0; ai < nAG; ai++)
                for (int pi = 1; pi < nPG - 1; pi++)
                { double dT = (gridDT[ai, pi + 1] - gridDT[ai, pi - 1]) / (2 * dpG); if (dT > 1e-8) pos++; else if (dT < -1e-8) neg++; }
            var posFrac = pos + neg > 0 ? (double)pos / (pos + neg) : 0;
            if (posFrac > 0.5) totalPos++; else totalNeg++;
            hubScore[fi] = posFrac;
            double fpE = 0, fpC = 0; int nE = 0, nC = 0;
            for (int ai = 0; ai < nAG; ai++)
                for (int pi = 1; pi < nPG - 1; pi++)
                { double fp = Math.Abs((gridDT[ai, pi + 1] - gridDT[ai, pi - 1]) / (2 * dpG)); if (pi <= 2 || pi >= nPG - 3) { fpE += fp; nE++; } else { fpC += fp; nC++; } }
            funnelScore[fi] = nC > 0 ? (fpE / Math.Max(nE, 1)) / (fpC / nC) : 1.0;
        }
        bool majPos = totalPos > totalNeg;
        for (int fi = 0; fi < nF; fi++) channelForm[fi] = (hubScore[fi] > 0.5) != majPos ? 1.0 : 0.0;

        int hubIdx = 0; double maxDT = double.MinValue;
        for (int fi = 0; fi < nF; fi++) if (dTdpRaw[fi] > maxDT) { maxDT = dTdpRaw[fi]; hubIdx = fi; }
        for (int fi = 0; fi < nF; fi++)
        {
            var fam = allFams[fi]; int ridges = 0;
            for (int ai = 0; ai < nAG; ai++)
            {
                for (int pi = 1; pi < nPG - 2; pi++)
                {
                    double U_h = ComputeGridPoint(allFams[hubIdx], ai, pi, aMin, daG, pMin, dpG, distances, sortedD, xiBase, k0Base);
                    double U_f = ComputeGridPoint(fam, ai, pi, aMin, daG, pMin, dpG, distances, sortedD, xiBase, k0Base);
                    double U_h1 = ComputeGridPoint(allFams[hubIdx], ai, pi + 1, aMin, daG, pMin, dpG, distances, sortedD, xiBase, k0Base);
                    double U_f1 = ComputeGridPoint(fam, ai, pi + 1, aMin, daG, pMin, dpG, distances, sortedD, xiBase, k0Base);
                    double U_hm = ComputeGridPoint(allFams[hubIdx], ai, pi - 1, aMin, daG, pMin, dpG, distances, sortedD, xiBase, k0Base);
                    double U_fm = ComputeGridPoint(fam, ai, pi - 1, aMin, daG, pMin, dpG, distances, sortedD, xiBase, k0Base);
                    double fp0 = -((U_h1 + U_f1) - (U_hm + U_fm)) / (2 * dpG);
                    double U_h2 = ComputeGridPoint(allFams[hubIdx], ai, pi + 2, aMin, daG, pMin, dpG, distances, sortedD, xiBase, k0Base);
                    double U_f2 = ComputeGridPoint(fam, ai, pi + 2, aMin, daG, pMin, dpG, distances, sortedD, xiBase, k0Base);
                    double fp1 = -((U_h2 + U_f2) - (U_h + U_f)) / (2 * dpG);
                    if (fp0 * fp1 < 0) { ridges++; break; }
                }
            }
            networkScore[fi] = (double)ridges; persistScore[fi] = nAG > 0 ? (double)ridges / nAG : 0;
        }

        // ================================================================
        // Generator covariance / PCA
        // ================================================================
        _o.WriteLine(new string('=', 108));
        _o.WriteLine("=== Generator Covariance & PCA ===");
        _o.WriteLine("");

        // Standardize generators
        var g1 = G.Select(g => g[0]).ToArray();
        var g2 = G.Select(g => g[1]).ToArray();
        var g3 = G.Select(g => g[2]).ToArray();

        // Covariance matrix of standardized generators
        var Zg1 = ZScore(g1); var Zg2 = ZScore(g2); var Zg3 = ZScore(g3);

        // 3×3 covariance
        double c11 = Zg1.Select((_, i) => Zg1[i] * Zg1[i]).Sum() / (nF - 1);
        double c22 = Zg2.Select((_, i) => Zg2[i] * Zg2[i]).Sum() / (nF - 1);
        double c33 = Zg3.Select((_, i) => Zg3[i] * Zg3[i]).Sum() / (nF - 1);
        double c12 = Zg1.Select((_, i) => Zg1[i] * Zg2[i]).Sum() / (nF - 1);
        double c13 = Zg1.Select((_, i) => Zg1[i] * Zg3[i]).Sum() / (nF - 1);
        double c23 = Zg2.Select((_, i) => Zg2[i] * Zg3[i]).Sum() / (nF - 1);

        _o.WriteLine("Covariance matrix (standardized):");
        _o.WriteLine($"         G1        G2        G3");
        _o.WriteLine($"  G1  {c11,8:F4}  {c12,8:F4}  {c13,8:F4}");
        _o.WriteLine($"  G2  {c12,8:F4}  {c22,8:F4}  {c23,8:F4}");
        _o.WriteLine($"  G3  {c13,8:F4}  {c23,8:F4}  {c33,8:F4}");
        _o.WriteLine("");

        // Jacobi eigenvalue decomposition (simple power iteration)
        var covG = new double[,] { { c11, c12, c13 }, { c12, c22, c23 }, { c13, c23, c33 } };
        var (eigvals, eigvecs) = EigenDecomp(covG, 3);

        Array.Sort(eigvals, eigvecs);
        Array.Reverse(eigvals);
        Array.Reverse(eigvecs);

        double totalVar = c11 + c22 + c33;
        _o.WriteLine("Eigenvalues:");
        _o.WriteLine($"  λ₁ = {eigvals[0]:F4}  ({eigvals[0] / totalVar * 100:F0}% variance)");
        _o.WriteLine($"  λ₂ = {eigvals[1]:F4}  ({eigvals[1] / totalVar * 100:F0}% variance)");
        _o.WriteLine($"  λ₃ = {eigvals[2]:F4}  ({eigvals[2] / totalVar * 100:F0}% variance)");
        _o.WriteLine("");

        // ================================================================
        // Latent Structure Map
        // ================================================================
        _o.WriteLine(new string('=', 108));
        _o.WriteLine("=== Latent Structure Map ===");
        _o.WriteLine("");

        // Project families onto PC1 and PC2
        var pc1Scores = new double[nF];
        var pc2Scores = new double[nF];
        for (int fi = 0; fi < nF; fi++)
        {
            pc1Scores[fi] = Zg1[fi] * eigvecs[0][0] + Zg2[fi] * eigvecs[0][1] + Zg3[fi] * eigvecs[0][2];
            pc2Scores[fi] = Zg1[fi] * eigvecs[1][0] + Zg2[fi] * eigvecs[1][1] + Zg3[fi] * eigvecs[1][2];
        }

        _o.WriteLine($"{"Family",-6} {"PC1",10} {"PC2",10} {"Mode",-10} {"dT/dp",-8} {"|m|",8} {"Region",-16}");
        _o.WriteLine(new string('-', 70));

        for (int fi = 0; fi < nF; fi++)
        {
            string mode = g1[fi] == 0 && g2[fi] == 0 && g3[fi] == 0 ? "MODE_C"
                : g1[fi] == 1 && g3[fi] == 1 ? "MODE_R"
                : g1[fi] == 1 ? "MODE_O" : "MODE_D";
            string sign = dTdpSign[fi] > 0 ? "POS" : "NEG";
            string region = dTdpSign[fi] > 0 ? "HUB" : "SPOKE";

            _o.WriteLine($"{allFams[fi],-6} {pc1Scores[fi],10:F4} {pc2Scores[fi],10:F4} {mode,-10} {sign,-8} {absM[fi],8:F4} {region,-16}");
        }
        _o.WriteLine("");

        // ================================================================
        // Latent factor reconstruction
        // ================================================================
        _o.WriteLine(new string('=', 108));
        _o.WriteLine("=== Latent Factor Reconstruction ===");
        _o.WriteLine("");

        _o.WriteLine("Can 1 or 2 latent factors reconstruct organizational outcomes?");
        _o.WriteLine("");

        var outcomes = new (string name, double[] values)[]
        {
            ("dT/dp sign", dTdpSign),
            ("Hub", hubScore),
            ("Channel", channelForm),
            ("Network", networkScore),
            ("Persistence", persistScore),
            ("Funnel", allFams.Select((_, i) => 1.0 / Math.Max(funnelScore[i], 0.01)).ToArray()),
            ("|m|", absM),
            ("Tick Curv", tickCurv),
        };

        _o.WriteLine($"{"Outcome",-14} {"3-gen R²",10} {"1-latent R²",12} {"2-latent R²",12} {"Best",-14} {"Latent sufficient?",18}");
        _o.WriteLine(new string('-', 82));

        int latent1Wins = 0, latent2Wins = 0, gen3Wins = 0;

        foreach (var ov in outcomes)
        {
            double r2_3gen = FitModelR2(ov.values, new[] { g1, g2, g3 });
            double r2_1latent = R2SinglePredictor(ov.values, pc1Scores);
            double r2_2latent = FitModelR2(ov.values, new[] { pc1Scores, pc2Scores });

            double best = Math.Max(r2_3gen, Math.Max(r2_1latent, r2_2latent));
            string winner = r2_1latent == best ? "1-LATENT" : r2_2latent == best ? "2-LATENT" : "3-GEN";
            if (winner == "1-LATENT") latent1Wins++;
            else if (winner == "2-LATENT") latent2Wins++;
            else gen3Wins++;

            string sufficient = r2_1latent > 0.8 ? "1 factor suffices"
                : r2_2latent > 0.9 ? "2 factors needed" : "3 generators needed";

            _o.WriteLine($"{ov.name,-14} {r2_3gen,10:F4} {r2_1latent,12:F4} {r2_2latent,12:F4} {winner,-14} {sufficient,-18}");
        }
        _o.WriteLine("");

        _o.WriteLine($"1-latent wins:  {latent1Wins}/{outcomes.Length}");
        _o.WriteLine($"2-latent wins:  {latent2Wins}/{outcomes.Length}");
        _o.WriteLine($"3-gen wins:     {gen3Wins}/{outcomes.Length}");
        _o.WriteLine("");

        // ================================================================
        // HUB/SPOKE in latent space
        // ================================================================
        _o.WriteLine(new string('=', 108));
        _o.WriteLine("=== HUB/SPOKE in Latent Space ===");
        _o.WriteLine("");

        _o.WriteLine("Does a single latent coordinate separate HUB from SPOKE?");
        _o.WriteLine("");

        double hubMeanPC1 = Enumerable.Range(0, nF).Where(fi => dTdpSign[fi] > 0).Average(fi => pc1Scores[fi]);
        double spokeMeanPC1 = Enumerable.Range(0, nF).Where(fi => dTdpSign[fi] < 0).Average(fi => pc1Scores[fi]);

        _o.WriteLine($"  HUB mean PC1:   {hubMeanPC1:F4}");
        _o.WriteLine($"  SPOKE mean PC1: {spokeMeanPC1:F4}");
        _o.WriteLine($"  Separation:      {Math.Abs(hubMeanPC1 - spokeMeanPC1):F4}");
        _o.WriteLine("");

        double r2_pc1_sign = R2SinglePredictor(dTdpSign, pc1Scores);
        double r2_pc2_sign = R2SinglePredictor(dTdpSign, pc2Scores);
        _o.WriteLine($"  PC1 → sign: R² = {r2_pc1_sign:F4}");
        _o.WriteLine($"  PC2 → sign: R² = {r2_pc2_sign:F4}");
        _o.WriteLine("");

        // ================================================================
        // Decision
        // ================================================================
        _o.WriteLine(new string('=', 108));
        _o.WriteLine("=== Decision ===");
        _o.WriteLine("");

        double pc1Var = eigvals[0] / totalVar;
        double pc2Var = eigvals[1] / totalVar;
        bool singleLatentDominates = pc1Var > 0.6 && latent1Wins >= 5;

        _o.WriteLine($"PC1 explains: {pc1Var * 100:F0}% of generator variance");
        _o.WriteLine($"PC2 explains: {pc2Var * 100:F0}% of generator variance");
        _o.WriteLine($"1-latent suffices for: {latent1Wins}/{outcomes.Length} outcomes");
        _o.WriteLine("");

        string classification;
        if (singleLatentDominates)
        {
            _o.WriteLine("VERDICT: SUPPORTED");
            _o.WriteLine("A SINGLE latent wave coordinate generates G1, G2, and G3.");
            classification = "SUPPORTED";
        }
        else if (pc1Var > 0.5 && latent1Wins >= 3)
        {
            _o.WriteLine("VERDICT: CONDITIONAL (1-latent dominant)");
            _o.WriteLine("PC1 captures majority of generator structure.");
            classification = "CONDITIONAL";
        }
        else if (pc1Var + pc2Var > 0.9)
        {
            _o.WriteLine("VERDICT: CONDITIONAL (2-latent required)");
            _o.WriteLine("Two latent factors needed for full reconstruction.");
            classification = "CONDITIONAL";
        }
        else
        {
            _o.WriteLine("VERDICT: FALSIFIED");
            _o.WriteLine("G1, G2, G3 are irreducible — no latent structure found.");
            classification = "FALSIFIED";
        }

        _o.WriteLine("");
        _o.WriteLine($"Classification: {classification}");
        _o.WriteLine("");

        _o.WriteLine("Wave Generator Principle:");
        _o.WriteLine($"  Generator variance: PC1={pc1Var*100:F0}%, PC2={pc2Var*100:F0}%, PC3={(eigvals[2]/totalVar)*100:F0}%");
        _o.WriteLine($"  Minimal latent dimension: {(singleLatentDominates ? 1 : pc1Var + pc2Var > 0.9 ? 2 : 3)}");
        _o.WriteLine("");

        _o.WriteLine(new string('=', 108));
        _o.WriteLine("=== WGP_03 complete. Commit: WGP_03_WaveGeneratorPrincipleAudit ===");
        Assert.True(true);
    }

    private static (double[] vals, double[][] vecs) EigenDecomp(double[,] mat, int n)
    {
        // Simple Jacobi eigenvalue algorithm for small symmetric matrices
        var a = new double[n, n];
        var v = new double[n][];
        for (int i = 0; i < n; i++) { v[i] = new double[n]; v[i][i] = 1.0; for (int j = 0; j < n; j++) a[i, j] = mat[i, j]; }

        for (int sweep = 0; sweep < 20; sweep++)
        {
            for (int p = 0; p < n - 1; p++)
                for (int q = p + 1; q < n; q++)
                {
                    if (Math.Abs(a[p, q]) < 1e-10) continue;
                    double theta = 0.5 * Math.Atan2(2.0 * a[p, q], a[q, q] - a[p, p]);
                    double c = Math.Cos(theta), s = Math.Sin(theta);
                    // Rotate a
                    double app = c * c * a[p, p] + s * s * a[q, q] + 2.0 * s * c * a[p, q];
                    double aqq = s * s * a[p, p] + c * c * a[q, q] - 2.0 * s * c * a[p, q];
                    a[p, q] = a[q, p] = 0;
                    a[p, p] = app; a[q, q] = aqq;
                    for (int r = 0; r < n; r++)
                    {
                        if (r == p || r == q) continue;
                        double arp = c * a[r, p] + s * a[r, q];
                        double arq = -s * a[r, p] + c * a[r, q];
                        a[r, p] = a[p, r] = arp;
                        a[r, q] = a[q, r] = arq;
                    }
                    // Rotate eigenvectors
                    for (int r = 0; r < n; r++)
                    {
                        double vrp = c * v[r][p] + s * v[r][q];
                        double vrq = -s * v[r][p] + c * v[r][q];
                        v[r][p] = vrp; v[r][q] = vrq;
                    }
                }
        }

        var vals = new double[n];
        var vecs = new double[n][];
        for (int i = 0; i < n; i++) { vals[i] = a[i, i]; vecs[i] = new double[n]; for (int j = 0; j < n; j++) vecs[i][j] = v[j][i]; }
        return (vals, vecs);
    }
}
